name: Deploy 😎

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:  
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  test:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository 👀
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: time-arena-game/Library
          key: Time-Arena-Library
      
      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        with:
          projectPath: time-arena-game
          githubToken: ${{ secrets.GITHUB_TOKEN }} 

  build:
    name: Build my project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository 👀
        uses: actions/checkout@v2
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v2
        with:
          path: time-arena-game/Library
          key: Time-Arena-Library

      # Build
      - name: Build project 🔨
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          projectpath: time-arena-game
          targetPlatform: WebGL

      # Output
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build